// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type User struct {
	ID         *string `json:"id"`
	FirstName  string  `json:"firstName"`
	LastName   string  `json:"lastName"`
	Status     string  `json:"Status"`
	Role       string  `json:"Role"`
	IsVerified bool    `json:"IsVerified"`
	IsActive   bool    `json:"IsActive"`
	Gender     string  `json:"Gender"`
	CreatedBy  string  `json:"CreatedBy"`
	UpdatedBy  string  `json:"UpdatedBy"`
	CreatedAt  string  `json:"CreatedAt"`
	UpdatedAt  string  `json:"UpdatedAt"`
	Email      string  `json:"Email"`
	Phone      string  `json:"Phone"`
	PhotoURL   *string `json:"PhotoUrl"`
}

type UserInput struct {
	ID         *string         `json:"id"`
	FirstName  string          `json:"firstName"`
	LastName   string          `json:"lastName"`
	Status     string          `json:"Status"`
	Role       string          `json:"Role"`
	IsVerified bool            `json:"IsVerified"`
	IsActive   bool            `json:"IsActive"`
	Gender     string          `json:"Gender"`
	CreatedBy  string          `json:"CreatedBy"`
	UpdatedBy  string          `json:"UpdatedBy"`
	Email      string          `json:"Email"`
	Phone      string          `json:"Phone"`
	Photo      *graphql.Upload `json:"Photo"`
	PhotoURL   *string         `json:"PhotoUrl"`
}

type UserLoginContext struct {
	User        *User  `json:"user"`
	AccessToken string `json:"access_token"`
}
