apiVersion: v1
kind: Service
metadata:
  name: {{ include "zicops-user-manager.name" . }}
  labels:
    app: {{ template "zicops-user-manager.name" . }}
    chart: {{ template "zicops-user-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: um-prod
      protocol: TCP
      name: um-prod
  selector:
    app: {{ template "zicops-user-manager.name" . }}
    release: {{ .Release.Name }}
