name: Go package

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.GO_MODULES_TOKEN }}
        run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/zicops/".insteadOf "https://github.com"

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v https://github.com/zicops/zicops-user-manager

      - name: Test
        run: go test -v ./...
