# Deploy to Staging

name: Concurrent-Deployment
run-name: Deployment-${{ github.event.inputs.environment }}

# setting concurrency at workflow level
concurrency: ${{ github.event.inputs.environment }}

# trigger event
on: 
 workflow_dispatch:
  inputs:
      environment:
       description: 'Environment'
       type: environment
       required: true
      
env:
  # Setting an environment variable with the value of approvers
  prod_approvers: ${{ vars.PRODUCTION_APPROVERS }}
  staging_approvers: ${{ vars.STAGING_APPROVERS }}
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: asia-south1-a
  SERVICE_NAME: zicops-user-manager
  

# Deploy  jobs

jobs:
#Initialize variables based on trigger branch (staging or main)
  initialize:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    outputs:
      GKE_CLUSTER: ${{ steps.setvars.outputs.GKE_CLUSTER }}${{ steps.setvars_staging.outputs.GKE_CLUSTER }}
      NAMESPACE: ${{ steps.setvars.outputs.NAMESPACE }}${{ steps.setvars_staging.outputs.NAMESPACE }}
      
    steps:
     - name: Initializing variables
       run: echo "Initializing variables..."
       

     - name: Set variables_production
       if: github.ref == 'refs/heads/main'
       id: setvars
       run: |
        echo "GKE_CLUSTER=zicops-dot-com-1" >> $GITHUB_OUTPUT
        echo "NAMESPACE = production" >> $GITHUB_OUTPUT
        
     - name: Set variables_staging
       if: github.ref == 'refs/heads/staging'
       id: setvars_staging
       run: |
        echo "GKE_CLUSTER=zicops-production-cost-one" >> $GITHUB_OUTPUT
        echo "NAMESPACE = staging" >> $GITHUB_OUTPUT



  Approvals:
    runs-on: ubuntu-latest
    needs: initialize
    steps:
      - name: Print
        run: echo ${{needs.initialize.outputs.GKE_CLUSTER}}
        
      - name: Get Approvals
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ngupta10
          
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
 # call-staging-deployment-workflow:
 #  needs: [Deployment]
 #  uses: Zicops/zicops-user-manager/.github/workflows/Reusable-zicops-cicd-um.yml@${GITHUB_REF##*/}
