# Deploy to Staging

name: Concurrent-Deployment
run-name: Deployment

# setting concurrency at workflow level
concurrency: Production

# trigger event
on: 
 workflow_dispatch:

      
env:
  # Setting an environment variable with the value of approvers
  prod_approvers: ${{ vars.PRODUCTION_APPROVERS }}
  staging_approvers: ${{ vars.STAGING_APPROVERS }}
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: asia-south1-a
  SERVICE_NAME: zicops-user-manager
  

# Deploy  jobs

jobs:
#Initialize variables based on trigger branch (staging or main)
  Initialize:
    runs-on: ubuntu-latest
    environment: Production
    env:
     BRANCH: test
    outputs:
      GKE_CLUSTER: ${{ steps.setvars_staging.outputs.GKE_CLUSTER }}
      NAMESPACE: ${{ steps.setvars_staging.outputs.NAMESPACE }}
      APPROVERS: ${{ steps.setvars_staging.outputs.appr }}
      
    steps:
     - name: Initializing variables
       run: echo "Initializing variables..."
        
     - name: Set variables_staging
       id: setvars_staging
       run: |
        echo "GKE_CLUSTER=zicops-production-cost-one" >> $GITHUB_OUTPUT
        echo "NAMESPACE=staging" >> $GITHUB_OUTPUT
        echo "appr=${{env.staging_approvers}}" >> $GITHUB_OUTPUT

      
    #Build Docker Image
  Build:
     runs-on: ubuntu-latest
     needs: [Initialize]
     steps:
     - uses: actions/checkout@v2
     - name: Auth GCP service account
       uses: 'google-github-actions/auth@v0'
       with:
         credentials_json: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
     - name: 'Set up Cloud SDK'
       uses: 'google-github-actions/setup-gcloud@v0'
     - name: 'Use gcloud CLI'
       run: 'gcloud info'
     - name: Build the Docker image
       run: |-
         docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA} --build-arg GO_MODULES_TOKEN=${{secrets.GO_MODULES_TOKEN}} .
     - name: add latest tag
       run: |-
        docker tag gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA} gcr.io/$PROJECT_ID/$SERVICE_NAME:latest    
     - run: |
        gcloud auth configure-docker -q
     - run: |
        gcloud components install gke-gcloud-auth-plugin
  
  # Get Approvals for Deployment
  Approvals:
    runs-on: ubuntu-latest
    needs: [Initialize, Build]
    steps:       
      - name: Get Approvals
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ needs.Initialize.outputs.APPROVERS }}
          minimum-approvals: 1
          issue-title: "Deploying to staging"
          exclude-workflow-initiator-as-approver: false

      
  
  call-staging-deployment-workflow:
   runs-on: ubuntu-latest
   needs: [Initialize,Approvals,Build]
   steps:
     - name: Initializing variables
       run: echo "Deploy Staging" 
  #call-staging-deployment-workflow:
   #needs: [Initialize,Approvals,Build]
   #uses: Zicops/zicops-user-manager/.github/workflows/Reusable-zicops-cicd-um.yml@main   
   #with:
    #GKE_CLUSTER: ${{ needs.Initialize.outputs.GKE_CLUSTER }}
    #GKE_ZONE: $GKE_ZONE
    #NAMESPACE: ${{ needs.Initialize.outputs.NAMESPACE }}
    #SERVICE_NAME: $SERVICE_NAME
   #secrets:
    #PROJECT_ID: $PROJECT_ID
    
    
  Initialize_Prod:
    runs-on: ubuntu-latest
    environment: Production
    needs: [Build,call-staging-deployment-workflow]
    env:
     BRANCH: test
    outputs:
      GKE_CLUSTER: ${{ steps.setvars.outputs.GKE_CLUSTER }}
      NAMESPACE: ${{ steps.setvars.outputs.NAMESPACE }}
      APPROVERS: ${{ steps.setvars.outputs.appr }}
      
    steps:
     - name: Initializing variables
       run: echo "Initializing variables..."     

     - name: Set variables_production
       id: setvars
       run: |
        echo "GKE_CLUSTER=zicops-dot-com-1" >> $GITHUB_OUTPUT
        echo "NAMESPACE=production" >> $GITHUB_OUTPUT
        cho "appr=${{env.production_approvers}}" >> $GITHUB_OUTPUT
        
    # Get Approvals for Deployment
  Approvals_Prod:
    runs-on: ubuntu-latest
    needs: [Initialize_Prod, Build,call-staging-deployment-workflow]
    steps:       
      - name: Get Approvals
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ needs.Initialize_Prod.outputs.APPROVERS }}
          minimum-approvals: 1
          issue-title: "Deploying to production"
          exclude-workflow-initiator-as-approver: false

  call-production-deployment-workflow:
   runs-on: ubuntu-latest
   needs: [Initialize_Prod, Build,call-staging-deployment-workflow,Approvals_Prod]
   steps:
     - name: Initializing variables
       run: echo "Deploy Staging"    
  #call-production-deployment-workflow:
   #needs: [Initialize_Prod, Build,call-staging-deployment-workflow,Approvals_Prod]
   #uses: Zicops/zicops-user-manager/.github/workflows/Reusable-zicops-cicd-um.yml@main   
   #with:
    #GKE_CLUSTER: ${{ needs.Initialize_Prod.outputs.GKE_CLUSTER }}
    #GKE_ZONE: $GKE_ZONE
    #NAMESPACE: ${{ needs.Initialize_Prod.outputs.NAMESPACE }}
    #SERVICE_NAME: $SERVICE_NAME
   #secrets:
    #PROJECT_ID: $PROJECT_ID

