name: Zicops App CI/CD - GCP Mumbai South-1-a

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: zicops-dot-com-1
  GKE_ZONE: asia-south1-a
  SERVICE_NAME: zicops-user-manager

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: export GITHUB_SHA
      run: echo "GITHUB_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

  build_push_image:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: export GITHUB_SHA
      run: echo "GITHUB_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Auth GCP service account
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |-
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA} --build-arg GO_MODULES_TOKEN=${{secrets.GO_MODULES_TOKEN}} .
    - name: add latest tag
      run: |-
        docker tag gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA} gcr.io/$PROJECT_ID/$SERVICE_NAME:latest
    - name: Push the Docker image
      run: |-
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA}
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:latest

  approval_stage:
    needs: build_push_image
    runs-on: ubuntu-latest
    steps:
    - name: Get Approvals for Staging Deployment
      uses: trstringer/manual-approval@v1.8.0
      with:
         secret: ${{ github.TOKEN }}
         approvers: saraswatpuneet,ngupta10, ansh5461
         minimum-approvals: 1
         issue-title: "Deploying to staging"
         exclude-workflow-initiator-as-approver: false

  deploy_staging:
    needs: approval_stage
    runs-on: ubuntu-latest
    steps:
    - name: Auth GCP service account
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - name: replace environment variable in values.yaml
      run:  envsubst '${GITHUB_SHA}' < k8s/zicops-user-manager/values.template.dev.yaml > k8s/zicops-user-manager/values.yaml
    - name: Deploy to zicops-prod-cost-one
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
          --zone $GKE_ZONE \
          --project $PROJECT_ID
        helm upgrade -n staging zicops-user-manager k8s/zicops-user-manager --install --wait --atomic

  approval_prod:
    needs: deploy_staging
    runs-on: ubuntu-latest
    steps:
    - name: Get Approvals for Zicops One Production Deployment
      uses: trstringer/manual-approval@v1.8.0
      with:
         secret: ${{ github.TOKEN }}
         approvers: saraswatpuneet,ngupta10,
         minimum-approvals: 1
         issue-title: "Deploying to zicops one production cluster"
         exclude-workflow-initiator-as-approver: false

  deploy_production:
    needs: approval_prod
    runs-on: ubuntu-latest
    steps:
    - name: Auth GCP service account
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - name: replace environment variable in values.yaml
      run:  envsubst '${GITHUB_SHA}' < k8s/zicops-user-manager/values.template.prod.yaml > k8s/zicops-user-manager/values.yaml
    - name: Deploy to zicops-prod-cost-one
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
          --zone $GKE_ZONE \
          --project $PROJECT_ID
        helm upgrade -n production zicops-user-manager k8s/zicops-user-manager --install --wait --atomic