name: Zicops App CI/CD - GCP Mumbai South-1-a

on:
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: zicops-dot-com-1
  GKE_ZONE: asia-south1-a

strategy:
  matrix:
    deployment: [staging, production]
    env:
      staging:
        NAMESPACE: staging
        SERVICE_NAME: zicops-user-manager
        TEMPLATE_FILE: k8s/zicops-user-manager/values.template.dev.yaml
      production:
        NAMESPACE: production
        SERVICE_NAME: zicops-user-manager
        TEMPLATE_FILE: k8s/zicops-user-manager/values.template.prod.yaml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

  authenticate:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Auth GCP service account
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'

  build_image:
    needs: authenticate
    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      run: |-
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA} --build-arg GO_MODULES_TOKEN=${{secrets.GO_MODULES_TOKEN}} .
    - name: add latest tag
      run: |-
        docker tag gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA} gcr.io/$PROJECT_ID/$SERVICE_NAME:latest

  approval:
    - name: Approval
      id: approval
      uses: actions/manual-approval@v2
      with:
        message: Approve before pushing the image to GCP

  push_image:
    needs: build_image
    runs-on: ubuntu-latest
    if: steps.approval.outputs.approved == 'true'
    steps:
    - name: Push image to GCP
      run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${GITHUB_SHA}
    - name: Push image to GCP
      run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:latest

  configure_values:
    needs: push_image
    runs-on: ubuntu-latest

    steps:
    - name: replace environment variable in values.yaml
      run:  envsubst '${GITHUB_SHA}' < $TEMPLATE_FILE > k8s/zicops-user-manager/values.yaml
  install_tools:
    needs: configure_values
    runs-on: ubuntu-latest

    steps:
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

  deploy:
    needs: install_tools
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to zicops-prod-cost-one
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
          --zone $GKE_ZONE \
          --project $PROJECT_ID
        helm upgrade -n $NAMESPACE zicops-user-manager k8s/zicops-user-manager --install --wait --atomic
