# Deploy to Staging

name: Staging-Concurrent-Deployment
run-name: Staging-Deployment-Test

# setting concurrency at workflow level
concurrency: Staging 

# need to add more trigger events?
on: 
 workflow_dispatch:
 push:
  branches: [ staging ]
 pull_request:
  branches: [ staging ]

# Deploy to staging jobs

jobs:
  Staging_deployment:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
     - uses: trstringer/manual-approval@v1
       with:
          secret: ${{ github.TOKEN }}
          approvers: ngupta10
     - name: Deploy to staging
       run: echo deploying
  call-workflow-1-in-local-repo:
   uses: zicops-user-manager/github/workflows/test_zicops-cicd-um.yml@staging

