name: Go package

on: [push,pull_request]



jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Configure git for private modules
      env:
        TOKEN: ${{ secrets.GO_MODULES_TOKEN }}
      run: git config --global url."https://${TOKEN}:x-oauth-basic@github.com/zicops/".insteadOf "https://github.com"
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
          go-version: ${{ matrix.go-version }}
        # You can test your matrix by printing the current Go version
    - name: Display Go version
      run: go version
       # Install all the dependencies
    - name: Install dependencies
      run: |
        go env -w GO111MODULE=off
        go version
        go get -u golang.org/x/lint/golint

    # - name: Build
     # run: go build -v https://@github.com/zicops/zicops-user-manager

    - name: Test
      run: go test -v https://@github.com/zicops/zicops-user-manager.git
