name: Go package

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.1*']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
        # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version

      - name: Build
        run: go build -v https://ngupta10:PhyCheMat02!@github.com/ngupta10/zicops-user-manager.git

      - name: Test
        run: go test -v ./...
